image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          name: Deploy Staging
          deployment: Staging
          caches:
            - node
            - gulp
          script:
            - npm install -g gulp
            - npm -s run install
            - npm -s run compile
            - apt-get update
            - apt-get install rsync -y
            - rsync -avz --exclude-from '.scripts/deploy/exclude-staging.txt' $THEME_DIR $STAGING_USER@$STAGING_HOST:$STAGING_PATH/$THEME_DIR --delete
    production:
      - step:
          name: Deploy Production
          deployment: Production
          caches:
            - node
            - gulp
          script:
            - npm install -g gulp
            - npm -s run install
            - npm -s run compile-production
            - apt-get update
            - apt-get install rsync -y
            - rsync -avz --exclude-from '.scripts/deploy/exclude-production.txt' $THEME_DIR $PRODUCTION_USER@$PRODUCTION_HOST:$PRODUCTION_PATH/$THEME_DIR --delete
            - ssh $PRODUCTION_USER@$PRODUCTION_HOST "cd $PRODUCTION_PATH; wp fastest-cache clear all; exit;"

definitions:
  caches:
    node: wp-content/themes/shiftr/node_modules
    gulp: /usr/local/lib/node_modules